repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-yaml
        args:
          - --unsafe
      - id: check-json
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-merge-conflict
      - id: detect-aws-credentials
        args: [--allow-missing-credentials]
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.77.1
    hooks:
      - id: terraform_fmt
      - id: terraform_validate
        # Exclude modules to work around
        # https://github.com/hashicorp/terraform/issues/28490
        exclude: "terraform/[^/]+/modules/[^/]+/[^/]+$"
      - id: terraform_tflint
  - repo: https://github.com/terraform-docs/terraform-docs
    rev: v0.16.0
    hooks:
      - id: terraform-docs-go
        name: Document cloud infrastructure remote state in README
        args: ["./terraform/s3-remote-state"]
      - id: terraform-docs-go
        name: Document cloud infrastructure in mkdocs
        args:
          [
            "./terraform/aws/modules/infra/",
            "--output-file",
            "../../../../docs/cloud-infrastructure.md",
          ]
      - id: terraform-docs-go
        name: Document Snowflake account infrastructure in mkdocs
        args:
          [
            "./terraform/snowflake/modules/elt/",
            "--output-file",
            "../../../../docs/snowflake.md",
          ]
  - repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
      - id: black
        language_version: python3
        args:
          - --target-version=py310
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.0.259
    hooks:
      - id: ruff
        args: [--show-source, --fix]
  - repo: https://github.com/codespell-project/codespell
    rev: v2.2.4
    hooks:
      - id: codespell
        types_or: [rst, markdown]
        files: docs
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.1.1
    hooks:
      - id: mypy
        args: [--warn-unused-configs]
        additional_dependencies:
          # Type stubs
          - pandas-stubs==v1.5.3.230321
          - types-requests
          - numpy
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.7.1
    hooks:
      - id: prettier
        types: [yaml]
  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.28.0
    hooks:
      - id: yamllint
        args: []
  - repo: local
    hooks:
      - name: Dbt deps
        id: dbt-deps
        language: python
        entry: dbt deps --project-dir=transform
        always_run: false
        pass_filenames: false
        types: [sql]
        additional_dependencies:
          - dbt-snowflake==1.5.1
          - dbt-core==1.5.2
  # Note: for SQLFluff we override the entrypoint for two reasons:
  #   1. dbt cloud looks for config in the dbt project directory, so we put it in
  #      transform/, however sqlfluff requires the templater config to be in the
  #      current working directory. So we have to cd to transform/ to properly set the
  #      templater config.
  #   2. Some machines (such as ODI Macs) seem to struggle with sqlfluff's
  #      multiprocessing implementation, so we force it to be single-process.
  - repo: https://github.com/sqlfluff/sqlfluff
    rev: 2.1.2
    hooks:
      - id: sqlfluff-lint
        entry: bash -c 'cd transform && sqlfluff lint --processes 1'
        additional_dependencies:
          - dbt-snowflake==1.5.1
          - sqlfluff-templater-dbt==2.1.2
          - dbt-core==1.5.2
      - id: sqlfluff-fix
        entry: bash -c 'cd transform && sqlfluff fix --processes 1'
        additional_dependencies:
          - dbt-snowflake==1.5.1
          - sqlfluff-templater-dbt==2.1.2
          - dbt-core==1.5.2
