repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-yaml
        args:
          - --unsafe
      - id: check-json
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-merge-conflict
      - id: detect-aws-credentials
        args: [--allow-missing-credentials]
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.12.1
    hooks:
      - id: ruff-check
        args: [--show-files, --fix]
      - id: ruff-format
  - repo: https://github.com/codespell-project/codespell
    rev: v2.2.4
    hooks:
      - id: codespell
        types_or: [rst, markdown]
        files: docs
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.1.1
    hooks:
      - id: mypy
        args: [--warn-unused-configs]
        additional_dependencies:
          # Type stubs
          - pandas-stubs==v2.2.3.250527
          - types-requests
          - numpy
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.7.1
    hooks:
      - id: prettier
        types: [yaml]
  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.28.0
    hooks:
      - id: yamllint
        args: []
  # Note: for SQLFluff we don't use the default pre-commit hook because
  # the pre-commit managed python environment can be difficult to install,
  # especially due to issues with pyarrow being brought in by Snowflake.
  # This keep things more predictable by using the uv.lock environment.
  - repo: local
    hooks:
      - id: sqlfluff
        name: sqlfluff
        language: system
        description: "Lints sql files with `SQLFluff`"
        types: [sql]
        require_serial: true
        entry: uv run sqlfluff fix --show-lint-violations --nocolor --disable-progress-bar
        pass_filenames: true
