site_name: CalData Data Services and Engineering Infrastructure
theme:
  name: material
  logo: images/odi-square_logomark-blue.svg
  favicon: images/odi-circle_logomark-blue.png
  features:
    - content.code.copy
  palette:
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
extra_css:
  - stylesheets/extra.css

repo_name: cagov/data-infrastructure
repo_url: https://github.com/cagov/data-infrastructure
edit_uri: ""

markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - pymdownx.highlight:
      auto_title: false
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

nav:
  - Introduction: index.md
  - Local Environment Setup: local-setup.md
  - Codespaces: codespaces.md
  - Code Review: code-review.md
  - Writing Documentation: writing-documentation.md
  - Naming Conventions: naming-conventions.md
  - Security Guidelines: security.md
  - Cloud Infrastructure: cloud-infrastructure.md
  - Project Architecture: architecture.md
  - Snowflake:
      - Snowflake Overview: snowflake.md
      - New Project Setup: snowflake-project-setup.md
  - dbt:
      - dbt Overview: dbt.md
      - dbt Performance: dbt-performance.md
      - dbt Snowflake Project: dbt_docs_snowflake/index.html
  - Data:
      - Building Footprints: data/footprints.md
  - Learning:
      - MDSA Glossary: learning/glossary.md
      - git: learning/git.md
      - dbt: learning/dbt.md
      - Cloud Data Warehouses: learning/cloud-data-warehouses.md
