site_name: CalData Data Services and Engineering Infrastructure
theme:
  name: material
  logo: images/odi-square_logomark-blue.svg
  favicon: images/odi-circle_logomark-blue.png
  features:
    - content.code.copy
  palette:
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
extra_css:
  - stylesheets/extra.css

repo_name: cagov/data-infrastructure
repo_url: https://github.com/cagov/data-infrastructure
edit_uri: ""

markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - pymdownx.highlight:
      auto_title: false
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

nav:
  - Introduction: index.md
  - Code Development:
      - Local Environment Setup: code/local-setup.md
      - Codespaces: code/codespaces.md
      - Code Review: code/code-review.md
      - Writing Documentation: code/writing-documentation.md
      - Terraform Setup: code/terraform-local-setup.md
  - Project Infrastructure:
      - Cloud Infrastructure: infra/cloud-infrastructure.md
      - Project Architecture: infra/architecture.md
      - Snowflake Overview: infra/snowflake.md
  - Project Setup:
      - Snowflake Setup: setup/snowflake-setup.md
      - Git/Github Setup: setup/repo-setup.md
      - Terraform Setup: setup/terraform-project-setup.md
      - Sentinel Setup: setup/sentinel-setup.md
      - dbt Setup: setup/dbt-setup.md
      - Adding Service Accounts: setup/snowflake-service-accounts.md
      - Project Teardown: setup/project-teardown.md
  - dbt:
      - dbt Overview: dbt/dbt.md
      - dbt Performance: dbt/dbt-performance.md
      - dbt Snowflake Project: dbt_docs_snowflake/index.html
  - Data:
      - Building Footprints: data/footprints.md
  - Learning:
      - MDSA Glossary: learning/glossary.md
      - Security Guidelines: learning/security.md
      - Naming Conventions: learning/naming-conventions.md
      - git: learning/git.md
      - dbt: learning/dbt.md
      - Cloud Data Warehouses: learning/cloud-data-warehouses.md
