config:
  send_anonymous_usage_stats: false
  use_colors: true
  warn_error: true

default:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: oauth
      project: "{{ env_var('GCP_PROJECT') }}"
      # Should not be created in CI as the CI service account is read-only!
      dataset: dbt_ci_should_not_create_this_dataset
      threads: 4
