name: base
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.10
  - fsspec
  - geopandas
  - mercantile
  - s3fs
  - pip
  - pip:
      - snowflake-connector-python[pandas]
      - pygris
