config:
  send_anonymous_usage_stats: false
  use_colors: true
  warn_error: true

dse_snowflake:
  target: snowflake_dev
  outputs:
    snowflake_dev:
      type: snowflake
      account: heb41095
      user: "{{ env_var('SNOWFLAKE_USER') }}"
      private_key: "{{ env_var('SNOWFLAKE_PRIVATE_KEY') }}"
      role: READER_DEV
      warehouse: REPORTING_XS_DEV
      database: ANALYTICS_DEV
      schema: ci_should_not_create_this_schema
      threads: 4
