default_language_version:
  python: python3.10
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-yaml
      - id: check-json
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.7.1
    hooks:
      - id: prettier
        types: [yaml]
  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.28.0
    hooks:
      - id: yamllint
        args: []
  - repo: https://github.com/tconbeer/sqlfmt
    rev: v0.13.0
    hooks:
      - id: sqlfmt
        language_version: python
  - repo: https://github.com/sqlfluff/sqlfluff
    rev: 2.0.0a6
    hooks:
      - id: sqlfluff-lint
        additional_dependencies:
          - dbt-bigquery==1.4.2
          - sqlfluff-templater-dbt==2.0.0a6
          - dbt-core==1.4.5
      - id: sqlfluff-fix
        additional_dependencies:
          - dbt-bigquery==1.4.2
          - sqlfluff-templater-dbt==2.0.0a6
          - dbt-core==1.4.5
