# Project name
name: "dse_analytics"
version: "1.0.0"
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: "default"

# These configurations specify where dbt should look for different types of files.
# The `source-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target" # directory which will store compiled SQL files
clean-targets: # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

models:
  ga4:
    staging:
      +schema: staging
    marts:
      +schema: google

  dse_analytics:
    staging:
      +database: TRANSFORM
      department_of_finance:
        +schema: department_of_finance

    intermediate:
      +database: TRANSFORM
      state_entities:
        +schema: state_entities

    marts:
      +database: ANALYTICS
      state_entities:
        +schema: state_entities

seeds:
  ga4:
    +schema: staging

vars:
  ga4:
    project: dse-product-analytics-prd-bqd
    # Note this is the statewide dataset, not the cagov-only.
    dataset: analytics_314711183
    start_date: "20221101"
    frequency: daily

tests:
  ga4:
    staging:
      ga4:
        not_null_stg_ga4__event_page_view_page_location:
          +enabled: false
