# Project name
name: "dse_analytics"
version: "1.0.0"
config-version: 2

flags:
  send_anonymous_usage_stats: false
  use_colors: true
  warn_error: false
  state_modified_compare_more_unrendered_values: true
  skip_nodes_if_on_run_start_fails: true
  require_explicit_package_overrides_for_builtin_materializations: true
  source_freshness_run_project_hooks: false

# This setting configures which "profile" dbt uses for this project.
profile: "dse_snowflake"

# These configurations specify where dbt should look for different types of files.
# The `source-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target" # directory which will store compiled SQL files
clean-targets: # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

models:
  dse_analytics:
    staging:
      +database: "{{ env_var('DBT_TRANSFORM_DB', 'TRANSFORM_DEV') }}"
      department_of_finance:
        +schema: department_of_finance
      snowflake_cost_tracking:
        +schema: snowflake_cost_tracking

    intermediate:
      +database: "{{ env_var('DBT_TRANSFORM_DB', 'TRANSFORM_DEV') }}"
      state_entities:
        +schema: state_entities

    marts:
      # All marts models as tables to avoid needing write access to TRANSFORM
      # https://community.snowflake.com/s/article/SQL-compilation-error-Failure-during-expansion-of-view-mySecureView
      +materialized: table
      +database: "{{ env_var('DBT_ANALYTICS_DB', 'ANALYTICS_DEV') }}"
      state_entities:
        +schema: state_entities
