name: pre-commit

on:
  pull_request:
  push:
    branches: [main]

defaults:
  run:
    shell: bash -l {0}

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - id: auth
        name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          # The credentials here can read metadata only, which makes them
          # good enough for `dbt compile`, but not good enough for
          # `dbt docs generate`. Should we want to do more detailed checks
          # at some point, we should revisit the service account permissions.
          credentials_json: ${{ secrets.GOOGLE_CREDENTIALS }}
          export_environment_variables: true
      - uses: actions/setup-python@v3
      - name: Install Conda environment with Micromamba
        uses: mamba-org/provision-with-micromamba@v15
        with:
          environment-file: ci/environment.yml
      - name: Build manifest and catalog
        env:
          DBT_PROFILES_DIR: ci
        run: dbt deps && dbt compile
      - uses: pre-commit/action@v3.0.0
        env:
          DBT_PROFILES_DIR: ci
