name: deploy

on:
  push:
    branches: [main, terraform-mvp]  # TODO remove branch

env:
  REGION: us-west-1
  DEFAULT_IMAGE_REPO: dse-infra-dev-ecr-us-west-1
  DEFAULT_IMAGE_NAME: analytics

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          # TODO: use OIDC for auth: https://github.com/aws-actions/configure-aws-credentials#assuming-a-role
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-1

      - run: aws ecr list-images --repository-name=dse-infra-dev-ecr-us-west-1
