name: submit

on:
  push:
    branches: [main, terraform-mvp]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          # TODO: use OIDC for auth: https://github.com/aws-actions/configure-aws-credentials#assuming-a-role
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-1
      - run: aws batch submit-job --job-name=test --job-queue=dse-infra-dev-batch-job-queue --job-definition dse-infra-dev-batch-job-definition
