name: terraform-checks

on:
  pull_request:
  push:
    branches: [main, tf_as_workflow]

env:
  TFLINT_LOG: debug

jobs:
  terraform-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          # terraform-docs suggests this type of checkout
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Setup terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: v1.4.0
      - name: Invoke terraform-docs
        uses: terraform-docs/gh-actions@v1.3.0
        with:
          working-dir: ./terraform/s3-remote-state
          git-push: "true"
      - name: Install tflint
        run: |
          curl -s https://raw.githubusercontent.com/terraform-linters/\
          tflint/master/install_linux.sh | bash
      - name: Run terraform fmt
        run: |
          terraform fmt
      - name: Run terraform validate
        run: |
          terraform validate
      - name: Run terraform tflint
        run: |
          tflint --chdir=terraform/ --recursive
