name: terraform-validation

on:
  pull_request:
  push:
    branches: [main]

jobs:
  terraform-validation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: v1.4.0
      - name: Install tflint
        run: |
          curl -s https://raw.githubusercontent.com/terraform-linters/\
          tflint/master/install_linux.sh | bash

      - name: Run terraform fmt
        run: |
          terraform fmt
      - name: Run terraform validate
        run: |
          terraform validate
      - name: Run terraform tflint
        run: |
          tflint --chdir=terraform/ --recursive
